### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by beackers** [BramvdnHeuvel/Rickroll-Generator#10]
Hi,
I'm new to this. So I tried running it, only under "https://some-rickroll-bro.com".
Is the generator supposed to make a new website ("https://some-rickroll-bro.com/<code>") or something else?

**Comment by BramvdnHeuvel** [comment]
On what ip address can users access the rickroll generator?

If you want users to connect through a domain name (like `some-rickroll-bro.com`) instead of an ip address, you need to buy the domain name. Once you've bought the domain, you can send people to your ip address where the server can be found.

**Comment by BramvdnHeuvel** [comment]
I'm closing this issue as a result of a lack of activity.
